description: >
  A minimal Debian-based executor suitable for running shell commands.

docker:
  - image: cimg/base:<<parameters.tag>>

parameters:
  tag:
    default: current
    description: >
      Pick a specific cimg/base tag:
      https://hub.docker.com/r/cimg/base/tags
    type: string
